{{- $fullname := include "etcd.fullname" . }}
{{- $labels := include "etcd.labels" . }}
{{- $selectorLabels := include "etcd.selectorLabels" . }}
{{- $serviceAccountName := include "etcd.serviceAccountName" . }}
{{- range $.Values.etcdinstances }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $fullname }}-{{ . }}
  labels:
    {{- $labels | nindent 4 }}
    etcd/instance: {{ . | quote }}
spec:
  storageClassName: {{ $.Values.storage.storageClass }}
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ $.Values.storage.patha }} 

{{- end }}
