{{- $fullname := include "etcd.fullname" . -}}
{{- $labels := include "etcd.labels" . -}}
{{- $selectorLabels := include "etcd.selectorLabels" . -}}
{{- $serviceAccountName := include "etcd.serviceAccountName" . -}}
{{- range $i, $e := tuple 0 1 2 -}}
{{- with $ -}}
{{- $instance := printf "%s-%d" $fullname $e -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $instance }}
  labels:
    {{- $labels | nindent 4 }}
    etcd/instance: {{ $instance }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      etcd/instance: {{ $instance }}
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- $selectorLabels | nindent 8 }}
        etcd/instance: {{ $instance }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $serviceAccountName }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            privileged: true
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: etcd
              protocol: TCP
              containerPort: 2379
            - name: cluster
              protocol: TCP
              containerPort: 2380
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          env:
            - name: ETCD_NAME
              value: {{ $instance }}.{{ .Release.Namespace}}.svc
            - name: ETCD_INSTANCE
              value: {{ $instance }}
            - name: ETCD_DATA_DIR
              value: /etcd-data/{{ $instance }}
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: http://{{ $instance }}.{{ .Release.Namespace}}.svc:2379
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: https://{{ $instance }}.{{ .Release.Namespace}}.svc:2380
            - name: ETCD_INITIAL_CLUSTER
              value: {{ $fullname }}-0=https://{{ $fullname }}-0.{{ .Release.Namespace}}.svc:2380,{{ $fullname }}-1=https://{{ $fullname }}-1.{{ .Release.Namespace}}.svc:2380,{{ $fullname }}-2=https://{{ $fullname }}-2.{{ .Release.Namespace}}.svc:2380
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: new
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: {{ $fullname }}
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ETCD_PEER_CERT-ALLOWED_CN
              value: storageos.svc 
          command:
            - /bin/sh
            - '-c'
            - >
              #!/bin/sh
    
              set -xeuo pipefail

              mkdir -p /etcd-data/${ETCD_INSTANCE}
    
              exec etcd \
                --experimental-initial-corrupt-check=true \
                --listen-peer-urls=https://0.0.0.0:2380 \
                --listen-client-urls=http://0.0.0.0:2379 \
                --peer-auto-tls \
                --cert-file=/etc/certs/private/tls.crt \
                --key-file=/etc/certs/private/tls.key 
          volumeMounts:
            - name: data
              mountPath: /etcd-data 
            - name: tls
              mountPath: /etc/certs/private
            - name: signed
              mountPath: /etc/certs/signed
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ $instance }}
        - name: tls
          secret:
            secretName: {{ $instance }}
        - name: signed
          configMap:
            name: {{ $fullname }}
            defaultMode: 420
      nodeSelector:
        {{ $fullname }}/node: {{ $instance }}
      tolerations:
        - operator: Exists
      priorityClassName: system-node-critical

{{ end }}
{{- end -}}
